# Generated by Django 2.2.16 on 2022-04-16 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='token',
            new_name='conficonfirmation_coderm',
        ),
    ]
